// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7lzGkhp7EsMARTQCyHk9VTYqY-tQKHWs',
    appId: '1:426168204246:web:6fcdb3bf24a4c0dbe5c277',
    messagingSenderId: '426168204246',
    projectId: 'doctorhelper-8e215',
    authDomain: 'doctorhelper-8e215.firebaseapp.com',
    storageBucket: 'doctorhelper-8e215.firebasestorage.app',
    measurementId: 'G-HG0LYN0079',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlEhjqPGCqhhHrZcj7H9gMqE_bmIjO6zM',
    appId: '1:426168204246:android:a86e1567206250fae5c277',
    messagingSenderId: '426168204246',
    projectId: 'doctorhelper-8e215',
    storageBucket: 'doctorhelper-8e215.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmg-VgnYeuv6nyjQ6yAjZRVvRIJ6NB1DM',
    appId: '1:426168204246:ios:b67f61e7df124276e5c277',
    messagingSenderId: '426168204246',
    projectId: 'doctorhelper-8e215',
    storageBucket: 'doctorhelper-8e215.firebasestorage.app',
    iosBundleId: 'com.example.doctorHelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmg-VgnYeuv6nyjQ6yAjZRVvRIJ6NB1DM',
    appId: '1:426168204246:ios:b67f61e7df124276e5c277',
    messagingSenderId: '426168204246',
    projectId: 'doctorhelper-8e215',
    storageBucket: 'doctorhelper-8e215.firebasestorage.app',
    iosBundleId: 'com.example.doctorHelper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7lzGkhp7EsMARTQCyHk9VTYqY-tQKHWs',
    appId: '1:426168204246:web:000d4892f61f90e2e5c277',
    messagingSenderId: '426168204246',
    projectId: 'doctorhelper-8e215',
    authDomain: 'doctorhelper-8e215.firebaseapp.com',
    storageBucket: 'doctorhelper-8e215.firebasestorage.app',
    measurementId: 'G-PJ60YBNHW3',
  );
}
